name: Deploy

on:
  push:
    branches:
      - main
  # Allow manual workflow triggers
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          BASE_URL: ${{ github.event.repository.name }}

      - name: Verify build
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed - dist directory not created"
            exit 1
          fi

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: 'Deploy: ${{ github.event.head_commit.message }}'
          full_commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
